### ISSUE TITLE
Machine Learning - Make predictions - AttributeError: 'EnumTypeWrapper' object has no attribute 'FLOAT'

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13425]
- Azure Data Studio Version:
Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/6405919/99217052-0358fb80-278c-11eb-9f04-3bf25231192d.png)

![MLMakePredictionsIssue](https://user-images.githubusercontent.com/6405919/99215360-81ff6a00-2787-11eb-8e56-91638ef8459a.gif)

The following repro assumes that you have already imported a Boston onnx model into your table. In case you don't, please unzip and import [boston model onnx file](https://github.com/microsoft/azuredatastudio/files/5544244/boston1.model.zip) first before you try to repro.

Steps to Reproduce:

1. Launch Machine Learning Extension on a SQL MI server. 
2. Click on Make Predictions
3. Choose "Import Model"
4. Choose an existing Boston onnx model in the model table. 
5. Click next to continue with Map Source Data to model. 

This error is going to appear. 

Error
Failed to load model parameters' Error: Process exited with code: 1. output: Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
AttributeError: 'EnumTypeWrapper' object has no attribute 'FLOAT'

**Comment by MsSQLGirl** [comment]
@llali, @udeeshagautam - can you please triage? thanks!

**Comment by llali** [comment]
@MsSQLGirl can you please send me the model? thanks

**Comment by MsSQLGirl** [comment]
I already did. Underneath the gif,  there is a link to the boston model file. Specifically - 
> The following repro assumes that you have already imported a Boston onnx model into your table. In case you don't, please unzip and import **[boston model onnx file](https://github.com/microsoft/azuredatastudio/files/5544244/boston1.model.zip)** first before you try to repro.

For your convenience, I'm adding it here again: https://github.com/microsoft/azuredatastudio/files/5544244/boston1.model.zip

**Comment by llali** [comment]
this is happening because protobuf version is old on that machine. I created the bug for onnx: https://github.com/onnx/onnx/issues/3134

**Comment by MsSQLGirl** [comment]
Talked to Leila. It seems that after upgrading protobuf to 3.12.2, the issue doesn't appear as much anymore. There is still an error when from time to time, from View Import Model dialog to Predict will not load the model correctly.
