### ISSUE TITLE
some projects failed to load after upgrading to v1.43.0

### ISSUE THREAD

**Issue by waylew-abc** [microsoft/azuredatastudio#22764]
- Azure Data Studio Version: 1.43.0
- OS Version: windows_NT x64 10.0.19045

Steps to Reproduce:

1. upgrade studio and database project to latest version (1.0.1)
2. open an existing database project file

Does this issue occur when all extensions are disabled?: No

 
getting this error in console logL

console.ts:137 [Extension Host] Error: Sequence contains no matching element
C @ console.ts:137
notificationsAlerts.ts:42 Some projects failed to load. To view more details, open the developer console
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR An unknown error occurred. Please consult the log f
[2023-04-18 08:31:47.813] [renderer1] [error] j is not a function: TypeError: j is not a function
    at l.queue (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:144:13167)
    at Q (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:144:12935)
    at _ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:409:30)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:169:47)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1326:38
    at _ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:632:39)

**Comment by kisantia** [comment]
@waylew-abc can you please share an example project that is no longer loading in 1.0.1? The project parsing was switched to use a different library in the 1.0.1 release, there's likely a bug there.

**Comment by simonsabin** [comment]
I've found a similar issue if you hav e SqlCmdVariables without default values, like this

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.9-preview" />
  <PropertyGroup>
    <Name>test</Name>
    <ProjectGuid>{C0162914-422D-4B59-9F95-487BF546475E}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
  <ItemGroup>
    <SqlCmdVariable Include="fsdfsd">
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
  </ItemGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
</Project>
```

**Comment by kisantia** [comment]
Thanks for providing a sample project that doesn't load @simonsabin! I'm working on a fix and hope to have the fix in insiders in the next couple days.

**Comment by Benjin** [comment]
I've created #22783 to for the issue where we're not surfacing a proper error message up from project parsing logic, which should be fixed even the optional default value bug resolved.

**Comment by kisantia** [comment]
Closing this issue since it is fixed in insiders and will be included in the next release. Please reopen if it isn't fixed or something else in the .sqlproj was causing the project not to load.
