### ISSUE TITLE
Restore dialog broken

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23257]
1.44/Insiders

Same issue as https://github.com/microsoft/azuredatastudio/issues/22839, which was fixed in https://github.com/microsoft/azuredatastudio/pull/22840

The problem was reintroduced in https://github.com/microsoft/azuredatastudio/pull/23104

I had added a test in the original fix that would have caught this, but unfortunately that was removed in a later PR that reverted the entire original feature : https://github.com/microsoft/azuredatastudio/pull/22997/files#diff-1f7cb57d04746810c6a813556ea08b667478f91cb7598f607d819cbe155d805eL287

**Comment by kburtram** [comment]
In my test environment I am able to open the restore dialog from the Manage dashboard, as a workaround.  I get the below exception when launching from OE.

```
log.ts:313   ERR this.getOptionKeyIdNames is not a function: TypeError: this.getOptionKeyIdNames is not a function
    at Object.getOptionsKey (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:165:5857)
    at Object.getOptionsKey (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:165:11379)
    at d (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:42:10543)
    at Object.b [as generateUri] (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:42:10356)
    at wa.getConnectionUri (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2710:27599)
    at vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2480:31836
    at new ZoneAwarePromise (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1351:25)
    at u.showDialog (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2480:31771)
    at o (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2224:1220)
    at d.invokeFunction (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:890:325)
    at s.runTask (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2224:2173)
    at handler (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1234:23683)
    at d.invokeFunction (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:890:325)
    at d._tryExecuteCommand (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2433:3665)
    at d.executeCommand (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2433:3022)
    at handler (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2224:3505)
```

**Comment by cheenamalhotra** [comment]
The only change in the linked PR was to move a part of function in a separate function. Adding the moved code to original function seems to resolve the error (but we also need the new function for commanLine use, so code would be duplicated.. we should look for a better solution long term).

The issue seems that the new function is not available when called from OE.. Does it mean OE is casting to a base type and is hiding functionalities from original type? 

We should also a test case that tests both types are identical always not just the options key - as we they are not interchangeable and we aren't able to add any new functions (private also doesn't work) to **ProviderConnectionInfo** independently until this design is fixed, otherwise we would continue facing this kind of issue from any part of the application.

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra The issue was caused by this line : https://github.com/microsoft/azuredatastudio/pull/23104/files#diff-f952231bc3fde12d411ad32e4e9fd058ae7127e1516fb230e077106f55fe858fR205

See the [original PR](https://github.com/microsoft/azuredatastudio/pull/22840) for why this breaks it (tl;dr, the "this" context is incorrect when the object is converted to an IConnectionProfile)

**Comment by kburtram** [comment]
Fix has been ported to hotfix branch.

**Comment by Charles-Gagnon** [comment]
Verified fixed in latest RC1 

Version: 1.44.1-rc1 (user setup)
Commit: 8f53a316fa00a98264f1ab119641cd540b5af25c
Date: 2023-06-01T02:04:55.463Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
